balanser:
  image: bezrukovp/main-balanser
  restart: always
  ports:
    - "80:80"
    - "443:443"
  links:
    - master
    - dev
    - monitor
master:
  image: bezrukovp/main-master
  restart: always
  ports:
    - "8893:8893"
    - "8894:8894"
    - "8895:8895"
  links:
    - database
    - memcached
dev:
  image: bezrukovp/main-dev
  restart: always
  links:
    - database
    - memcached
  environment:
    - DEBUG=true
database:
  image: bezrukovp/main-database
  restart: always
  ports:
    - "3306:3306"
memcached:
  image: bezrukovp/main-memcached
  restart: always
monitor:
  image: bezrukovp/main-monitor
  restart: always