balanser:
  image: bezrukovp/main-balanser
  restart: always
  ports:
    - "80:80"
    - "443:443"
    - "2220:22"
  links:
    - php-master
    - php-dev
    - monitor
php-master:
  image: bezrukovp/main-php-master
  restart: always
  ports:
    - "2221:22"
    - "8893:8893"
    - "8894:8894"
    - "8895:8895"
  links:
    - mail
    - database-mysql
    - memcached
    - sphinx
php-dev:
  image: bezrukovp/main-php-dev
  restart: always
  ports:
    - "2231:22"
  links:
    - mail
    - database-mysql
    - memcached
    - sphinx
  environment:
    - DEBUG=true
database-mysql:
  image: bezrukovp/main-database-mysql
  restart: always
  ports:
    - "2211:22"
    - "3306:3306"
mail:
  image: bezrukovp/main-mail
  restart: always
  ports:
    - "2240:22"
memcached:
  image: bezrukovp/main-memcached
  restart: always
  ports:
    - "2241:22"
sphinx:
  image: bezrukovp/main-sphinx
  restart: always
  ports:
    - "2242:22"
  links:
    - database-mysql
monitor:
  image: bezrukovp/main-monitor
  restart: always
  ports:
    - "2230:22"
  links:
    - mail